Resources:
  SpokenFormsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "fullName"
          AttributeType: "S"        
      KeySchema:
        - AttributeName: "fullName"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "spokenForms"
  SpokenFormUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
        - AttributeName: "spokenFormFullName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
        - AttributeName: "spokenFormFullName"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "spokenFormUsers"
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "users"